apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
  namespace: weather-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
      - name: consumer
        image: kafka-consumer-go:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: KAFKA_BROKERS
          value: "kafka-broker-0.kafka-broker-headless.weather-system.svc.cluster.local:9092"
        - name: REDIS_URL
          value: "redis://valkey-service.weather-system.svc.cluster.local:6379"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
