apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-processor-go
  namespace: weather-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-processor-go
  template:
    metadata:
      labels:
        app: weather-processor-go
    spec:
      containers:
      - name: processor
        image: weather-processor-go:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
          name: http
        - containerPort: 50051
          name: grpc
        env:
        - name: KAFKA_BROKERS
          value: "kafka-broker-0.kafka-broker-headless.weather-system.svc.cluster.local:9092"
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq-service.weather-system.svc.cluster.local:5672/"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 5
