apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-api-rust
  namespace: weather-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-api-rust
  template:
    metadata:
      labels:
        app: weather-api-rust
    spec:
      containers:
      - name: weather-api
        image: weather-api-rust:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: RUST_LOG
          value: "info"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
