FROM python:3.11-slim

WORKDIR /app

COPY scripts/locustfile.py .
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8089

CMD ["locust", "-f", "locustfile.py", "--host", "http://weather-api-service:8080"]
