apiVersion: v1
kind: Service
metadata:
  name: valkey-service
  namespace: weather-system
spec:
  type: ClusterIP
  selector:
    app: valkey
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
