apiVersion: v1
kind: Service
metadata:
  name: weather-api-service
  namespace: weather-system
spec:
  type: ClusterIP
  selector:
    app: weather-api-rust
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
