apiVersion: v1
kind: Service
metadata:
  name: weather-processor-service
  namespace: weather-system
spec:
  type: ClusterIP
  selector:
    app: weather-processor-go
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP
  - name: grpc
    port: 50051
    targetPort: 50051
    protocol: TCP
