apiVersion: v1
kind: Namespace
metadata:
  name: zot-registry
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zot-config
  namespace: zot-registry
data:
  config.json: |
    {
      "distSpecVersion": "1.1.0",
      "storage": {
        "rootDirectory": "/var/lib/zot",
        "dedupe": true,
        "gc": true,
        "gcDelay": "2h"
      },
      "http": {
        "address": "0.0.0.0",
        "port": "5000",
        "realm": "Zot",
        "auth": {
          "bearer": {
            "realm": "https://auth.example.com/auth",
            "service": "zot-server"
          }
        }
      },
      "log": {
        "level": "info",
        "output": "stdout"
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zot
  namespace: zot-registry
  labels:
    app: zot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zot
  template:
    metadata:
      labels:
        app: zot
    spec:
      containers:
      - name: zot
        image: ghcr.io/project-zot/zot-linux-amd64:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          name: http
        volumeMounts:
        - name: config
          mountPath: /etc/zot
        - name: storage
          mountPath: /var/lib/zot
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /v2/
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /v2/
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: config
        configMap:
          name: zot-config
      - name: storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: zot
  namespace: zot-registry
  labels:
    app: zot
spec:
  selector:
    app: zot
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: zot-lb
  namespace: zot-registry
  labels:
    app: zot
spec:
  selector:
    app: zot
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  type: LoadBalancer
